# Generated by Django 2.0.6 on 2018-06-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
                ('temp', models.FloatField()),
                ('pressure', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together={('city_name', 'date')},
        ),
    ]
